CREATE PROC FIRMAHAREKETLERI
AS
SELECT TBL_FIRMAHAREKETLER.ID,URUNAD,TBL_FIRMAHAREKETLER.ADET,
(TBL_PERSONELLER.AD + ' ' + TBL_PERSONELLER.SOYAD) AS 'AD SOYAD',
TBL_FIRMALAR.AD,FIYAT,TOPLAM,FATURAID,TARIH,NOTLAR
FROM TBL_FIRMAHAREKETLER
INNER JOIN
TBL_URUNLER
ON
TBL_FIRMAHAREKETLER.URUNID = TBL_URUNLER.ID
INNER JOIN
TBL_PERSONELLER
ON
TBL_FIRMAHAREKETLER.PERSONEL=TBL_PERSONELLER.ID
INNER JOIN
TBL_FIRMALAR
ON
TBL_FIRMAHAREKETLER.FIRMA= TBL_FIRMALAR.ID
