CREATE PROC FIRMASONON
AS
SELECT TOP 10 URUNAD,TBL_FIRMAHAREKETLER.ADET,
TBL_FIRMALAR.AD,FIYAT,TOPLAM,TARIH
FROM TBL_FIRMAHAREKETLER
INNER JOIN
TBL_URUNLER
ON
TBL_FIRMAHAREKETLER.URUNID = TBL_URUNLER.ID
INNER JOIN
TBL_PERSONELLER
ON
TBL_FIRMAHAREKETLER.PERSONEL=TBL_PERSONELLER.ID
INNER JOIN
TBL_FIRMALAR
ON
TBL_FIRMAHAREKETLER.FIRMA= TBL_FIRMALAR.ID
ORDER BY TBL_FIRMAHAREKETLER.ID 