CREATE PROC MUSTERIHAREKETLER
AS
SELECT TBL_MUSTERIHAREKETLER.ID,URUNAD,TBL_MUSTERIHAREKETLER.ADET,
(TBL_PERSONELLER.AD+''+TBL_PERSONELLER.SOYAD) AS 'PERSONEL',
(TBL_MUSTERILER.AD+''+TBL_MUSTERILER.SOYAD) AS 'MUSTERI',
FIYAT,TOPLAM,TARIH,NOTLAR
FROM TBL_MUSTERIHAREKETLER
INNER JOIN
TBL_URUNLER
ON
TBL_MUSTERIHAREKETLER.URUNID=TBL_URUNLER.ID
INNER JOIN
TBL_PERSONELLER
ON
TBL_MUSTERIHAREKETLER.PERSONEL=TBL_PERSONELLER.ID
INNER JOIN
TBL_MUSTERILER
ON
TBL_MUSTERIHAREKETLER.MUSTERI=TBL_MUSTERILER.ID

EXEC MUSTERIHAREKETLER