--CREATE PROC BANKABILGILERI
--AS 
--SELECT TBL_BANKALAR.ID,BANKAADI,TBL_BANKALAR.IL,TBL_BANKALAR.ILCE,SUBE,IBAN,HESAPNO,YETKILI,TELEFON,TARIH,HESAPTURU,AD 
--FROM TBL_BANKALAR
--INNER JOIN TBL_FIRMALAR
--ON
--TBL_BANKALAR.FIRMAID = TBL_FIRMALAR.ID

EXEC BANKABILGILERI