CREATE PROC FATURADETAY
AS
SELECT FATURAURUNID,URUNAD,MIKTAR,FIYAT,TUTAR,ALICI 
FROM TBL_FATURADETAY
INNER JOIN TBL_FATURABILGI
ON
TBL_FATURADETAY.FATURAID = TBL_FATURABILGI.FATURAID

EXEC FATURADETAY