CREATE TRIGGER STOKSILME
ON TBL_FATURADETAY
AFTER DELETE
AS
DECLARE @model varchar(20)
DECLARE @eski smallint
SELECT @eski=MIKTAR FROM deleted
SELECT @model=MODEL FROM deleted
BEGIN
UPDATE TBL_URUNLER SET ADET=(ADET+@eski) WHERE MODEL=@model
END


