CREATE TRIGGER STOKSILME
ON TBL_FATURADETAY
AFTER DELETE
AS
DECLARE @model varchar(20)
DECLARE @eski smallint,@IDF int
DECLARE @durum bit
SELECT @eski=MIKTAR FROM deleted
SELECT @model=MODEL FROM deleted
SELECT @durum=DURUM2 FROM deleted
SELECT @IDF=FATURAID FROM deleted
BEGIN
IF @durum=1
BEGIN
UPDATE TBL_URUNLER SET ADET=(ADET+@eski) WHERE MODEL=@model
END
END