ALTER TRIGGER STOKAZALTMA
ON TBL_FATURADETAY
AFTER UPDATE
AS
DECLARE @seri varchar(20)
DECLARE @yeni smallint
SET @yeni=(SELECT TOP 1 MIKTAR FROM TBL_FATURADETAY ORDER BY FATURAURUNID DESC)
SET @seri=(SELECT TOP 1 MODEL FROM TBL_FATURADETAY WHERE FATURAURUNID)
BEGIN
UPDATE TBL_URUNLER SET ADET=(ADET-@yeni) WHERE MODEL=@seri
END



